### ISSUE TITLE
listening to midi start/stop/continue messages

### ISSUE THREAD

**Issue by jsilence** [tehn/awake#16]
Dear tehn, thanks a lot for this wonderful script. I like it a lot.
For more convenient sampling sequences into my Deluge I implemented start/stop/continue in the script.
[awake-start-stop.lua.txt](https://github.com/tehn/awake/files/6836353/awake-start-stop.lua.txt)

Feel free to integrate. Or would you prefer a pull request? 
If you like it, I could implement a toggle parameter for the users to choose whether they want this behaviour.

**Comment by tehn** [comment]
PR would be great thank you!
