### ISSUE TITLE
No README?

### ISSUE THREAD

**Issue by microfx** [tehn/awake#21]
Expected a manual / readme when coming here. ❤️

**Comment by tehn** [comment]
this is a script for norns--- we didn't really set out to have READMEs as a design pattern (but i agree there should be one)--- rather, the URL for instructions/etc are the third line of the code, which displays on the screen as the script detail prior to loading: https://github.com/tehn/awake/blob/master/awake.lua#L3

we even made an llll url shortener for easy typing to facilitate this sort of in-system hyperlinking w/o requiring people to know about github/etc
